config/routes.rb
Bowling::Application.routes.draw do
  resources :frames

  resources :matches

  resources :players

  resources :score

  root 'matches#index'

  

end

app/models/match.rb
class Match < ActiveRecord::Base
	has_many :players, :dependent => :destroy

  def current_player_name
  	players.where(:played => 0).first.name
  end

  def current_player
		players.where(:played => 0).first
  end

  def player_count
    players.size
  end

  def update_score score
  	player = current_player
    if player.bonus != 0
      if player.bonus == 1
        frame = player.frames.last
        frame.update_attributes(:try3 => score, :completed => true)
        s = check_score(score)
        s = player.read_attribute(:score) + s
        player.update_attributes(:score => s)
        player.update_attributes(:played => 1)
        player.update_frame_scores
      else
        frame = player.frames.last
        if frame.read_attribute(:try2) == nil
          frame.update_attributes(:try2 => score)
          s = check_score(score)
          s = player.read_attribute(:score) + s
          player.update_attributes(:score => s)
        else
          frame.update_attributes(:try3 => score, :completed => true)
          s = check_score(score)
          s = player.read_attribute(:score) + s
          player.update_attributes(:score => s)
          player.update_attributes(:played => 1)
          player.update_frame_scores
        end
      end
      return
    end

  	if player.frames.any? 
      if player.frames.where(:completed => false).size > 0
  		  frame = player.frames.last
  		  frame.update_attributes(:try2 => score, :completed => true)
        s = check_score(score)
        if (frame.read_attribute(:try1) + score.to_i == 10)
          s = '/'
          if (self.frame == 10)
              bonus(player, 1, s)
            return
          end
        end
        s = player.read_attribute(:score) + s
  		  player.update_attributes(:score => s)
  		  player.update_attributes(:played => 1)
        player.update_frame_scores
      else
        frame = player.frames.create(:try1 => score, :completed => false, :number => self.frame, :total => 0)
        s = check_score(score)
        if (s == 'X')
          if (self.frame == 10)
              bonus(player, 2, s)
            return
          else
            strike(player, s)
          end
        else 
          s = player.read_attribute(:score) + s
          player.update_attributes(:score => s)
        end
      end


  	else
  		frame = player.frames.create(:try1 => score, :completed => false, :number => self.frame, :total => 0)

      s = check_score(score)
      if (s == 'X')
        strike(player, s)
      else 
  		  s = player.read_attribute(:score) + s
        player.update_attributes(:score => s)
      end
  	end

    end_of_round

  end

  def strike player, s
    frame = player.frames.last
    frame.update_attributes(:completed => true)
    player.update_attributes(:played => 1)
    s = player.read_attribute(:score) + s
    player.update_attributes(:score => s)
    player.update_frame_scores
  end

  def bonus player, number, s
    player.update_attributes(:bonus => number)
    s = player.read_attribute(:score) + s
    player.update_attributes(:score => s)
    player.update_attributes(:played => 0)
  end

  def end_of_round
    if !end_of_game && players.where(:played => 0).size == 0
      players.update_all(:played => 0)
      if self.frame < 10
        frame_number = self.frame + 1;   
        self.update_attributes(:frame => frame_number)
      end
    end
  end

  def end_of_game
    if self.frame == 10
      if players.where(:played => 0).size == 0
        return true
      end
    end
  end

  def winner 
    ary = Array.new
    a = 0
    max = 0
    players.each do |player|
      if max <= player.get_points
        if max < player.get_points
          a = 0
          max = player.get_points
          ary.clear
          ary[a] = player
          a += 1
        else 
          max = player.get_points
          ary[a] = player   
          a += 1    
        end
      end
   end
   return ary
  end


  def check_score score
    if score == '10'
      return 'X'
    elsif score == '0'
      return '-'
    else
      return score
    end
  end

  def started
    players.each do |player| 
      if player.frames.any?
        return true
      end
    end
    return false
  end

  validates :name, :presence => true
  validates :name, :uniqueness => true

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @frame = Frame.new
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)
    @match.frame = 1

    respond_to do |format|
      if @match.save
        format.html { redirect_to matches_path}
        format.json { render action: 'show', status: :created, location: @match }
      else
        format.html { render action: 'new' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match name successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
 end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:name)
    end






end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %> 
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/_scoreboard.html.erb
<p>
  <strong><h1><%= @match.name %> </h1></strong>
  <h2>Frame <%= @match.frame %> </h2>
</p>

<table>
  <tr>
    <th> Name</th>
    <th> Score </th>
    <th> Points </th>
  </tr>

<% @match.players.each do |player| %>
  <tr>
    <td>
      <%= player.name %> </br>
    </td>
    <td>
      <%= render partial: "matches/scoresheet", locals: {player: player} %>
    </td>
    <td>
      <center><%= player.get_points %> </br></center>
    </td>
  </tr>
<% end %>
</table>

app/views/matches/_scoresheet.html.erb
<table border="1" cellspacing="1" cellpadding="4">
  <tr>
    <% for i in 1..10 %>
      <th width="50" colspan="3"><center><%= i %></center></th> 
    <% end %>
  </tr>
    
  <% a = 0 %>  
  <% b = 0 %>
  <tr>

    <% while a < player.score.length %>
      <% if b >= 9 %>
        <td><center><%=player.score[a]%></center></td>
        <% b += 1 %>
        <% a += 1 %>
      <% elsif player.score[a] == 'X' %>
          <% b += 1 %>
          <td colspan="2"></td>
          <td><center>X</center></td>
          <% a += 1 %>
      <% else %>
          <% b += 1 %>
          <td colspan="2"><center><%= player.score[a] %><center></td>
          <td><center><%= player.score[a+1] %><center></td>
          <% a += 2 %>       
      <% end %>
    <% end %>

    <% if b < 10 %>
      <% b = 9-b %>
      <% for a in 0..b %>
        <% if a == b %>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        <% else %>
          <td colspan="2">&nbsp;</td>
          <td>&nbsp;</td>
        <% end %>
      <% end %>
    <% end %>

  </tr>

  <% a = 0 %>  
  <tr>
    <% player.frames.each do |f| %>
      <td colspan="3">
        <center><%= f.read_attribute(:total) %></center>
      </td>   
      <% a += 1 %>
    <% end %>

    <% a = 9-a %>
    <% for c in 0..a %>
      <td colspan="3"><center>&nbsp;</center></td>
    <% end %>
  </tr>
</table>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>List of Matches</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.name %></td>
        <td><%= link_to 'Delete', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <!-- if match has started, can't add new players -->
        <% if !match.started %>
          <td><%= link_to 'Add Players', players_url(:match_id => match.id) %></td>
        <% else %>
          <td>&nbsp;</td>
        <% end %>
        <!-- if match has no players, can't start game -->
        <% if match.players.size != 0 %>
          <% if match.end_of_game %>
            <td>&nbsp;</td>
            <td><%= link_to 'See Results', match %></td>     
          <% else %>
            <td><%= link_to 'Return To Game', match %></td>
            <td>&nbsp;</td>
          <% end %>
        <% else %>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>
<br>

<%= link_to 'Create New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<br><br><br>
<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<div id="scoreboard">
  <%= render partial: "scoreboard" %>
</div>


<br>
<br>

<b>=========================================</b>

<% if !@match.end_of_game %>

  <h2><b><u><%= @match.current_player_name %></b>'s Turn</u></h2>

  <br>

  Enter Score: 
  <%= render 'frames/form' %>

  <br>
  <br>
  <br>

  <%= link_to 'Quit Game', matches_url %>

<% else %>

  <h2><b>
  <% winners = @match.winner %>
  <% if winners.size == 1 %>
    <%= winners[0].name %> is the winner
  <% else %>
    <% for i in 0..winners.size-1 %>
      <%= winners[i].name %>,&nbsp
    <% end %>
    are the winners
  <% end %>
  </b></h2>

  <br>
  <br>
  <br>

  <%= link_to 'Back', matches_url %>

<% end %>