config/routes.rb
Bowling::Application.routes.draw do
  resources :frames

  resources :matches

  resources :players

  resources :score

  root 'matches#index'

  

end

app/models/frame.rb
class Frame < ActiveRecord::Base
	belongs_to :player
  def check_score score
    if score == '10'
      return 'X'
    elsif score == '0'
      return '-'
    else
      return score
    end
  end
end

app/controllers/frames_controller.rb
class FramesController < ApplicationController
  before_action :set_frame, only: [:show, :edit, :update, :destroy]

  # GET /frames
  # GET /frames.json
  def index
    @frames = Frame.all
    if params[:frame_number]
      session[:frame_number] = params[:frame_number]
    end
    if params[:player_id]
      session[:player_id] = params[:player_id]
    end
    @player = session[:player_id]
  end

  # GET /frames/1
  # GET /frames/1.json
  def show
  end

  # GET /frames/new
  def new
    @frame = Frame.new
  end

  # GET /frames/1/edit
  def edit
  end

  # POST /frames
  # POST /frames.json
  def create
    @frame = Frame.new(frame_params)
    @frame.try1 = 0
    @frame.try2 = 0
    @frame.total = 0
    @frame.game_id = session[:player_id]  
    @frame.completed = false
    @frame.number = 1

    respond_to do |format|
      if @frame.save
        format.html { redirect_to @frame, notice: 'Frame was successfully created.' }
        format.json { render action: 'show', status: :created, location: @frame }
      else
        format.html { render action: 'new' }
        format.json { render json: @frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frames/1
  # PATCH/PUT /frames/1.json
  def update
    respond_to do |format|
      if @frame.update(frame_params)
        format.html { redirect_to @frame, notice: 'Frame was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frames/1
  # DELETE /frames/1.json
  def destroy
    @frame.destroy
    respond_to do |format|
      format.html { redirect_to frames_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frame
      @frame = Frame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frame_params
      params.require(:frame).permit(:try1, :try2integer, :number)
    end
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/views/frames/_form.html.erb
<%= form_for("score", :url => score_url(session[:match_id]), :html => { :method => :put }, :remote => true) do |f| %>
  <!-- form_for("score", :url => {:controller => "score", :action => "update"}) -->
  <% if @frame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frame.errors.count, "error") %> prohibited this frame from being saved:</h2>

      <ul>
      <% @frame.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.number_field :value %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/frames/edit.html.erb
<h1>Editing frame</h1>

<%= render 'form' %>

<%= link_to 'Show', @frame %> |
<%= link_to 'Back', frames_path %>

app/views/frames/index.html.erb
<h1>Listing frames</h1>

<table>
  <thead>
    <tr>
      <th>Try1</th>
      <th>Try2</th>
      <th>Number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @frames.each do |frame| %>
      <tr>
        <td><%= frame.try1 %></td>
        <td><%= frame.try2 %></td>
        <td><%= frame.number %></td>
        <td><%= link_to 'Show', frame %></td>
        <td><%= link_to 'Edit', edit_frame_path(frame) %></td>
        <td><%= link_to 'Destroy', frame, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Frame', new_frame_path %>

app/views/frames/new.html.erb
<h1>New frame</h1>

<%= render 'form' %>

<%= link_to 'Back', frames_path %>

app/views/frames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Try1:</strong>
  <%= @frame.try1 %>
</p>

<p>
  <strong>Try2:</strong>
  <%= @frame.try2%>
</p>

<p>
  <strong>Number:</strong>
  <%= @frame.number %>
</p>

<%= link_to 'Edit', edit_frame_path(@frame) %> |
<%= link_to 'Back', frames_path %>